/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PrintFuncs */

#ifndef _Included_PrintFuncs
#define _Included_PrintFuncs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PrintFuncs
 * Method:    printStringNative
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_PrintFuncs_printStringNative
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
